version: '3.4'

services:

  cfssl:
    image: cfssl/cfssl
    working_dir: /ssl
    volumes:
      - ./runtime/ssl:/ssl
    entrypoint: ./gen-cert.sh

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    env_file: .env.sample

  memcached:
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  web-ssl:
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./runtime/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./runtime/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - cfssl

  web:
    build:
      context: .
    expose:
      - "80"
    volumes:
      - ./runtime/ssl:/etc/apache2/ssl
    env_file: .env.sample
    environment:
      ENVIRONMENT: local
      SITE_URL: "http://localhost"
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: "11211"
    depends_on:
      - db

volumes:
  database:
